/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miini;
import java.sql.DriverManager;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.sql.Connection;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Darshan
 */
public class availability extends javax.swing.JFrame {
Connection con;
Statement st;
PreparedStatement ps;
ResultSet rs;

    /**
     * Creates new form availability
     */
    public availability() {
        initComponents();
        try{
Class.forName("oracle.jdbc.OracleDriver");
//JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
con = DriverManager.getConnection("jdbc:oracle:thin:@JK:1521:XE",
                        "system", "jk");
//JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(connect.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
catch(ClassNotFoundException ex){
Logger.getLogger(connect.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TRAIN_NO = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        REM_CC = new javax.swing.JTextField();
        REM_SL = new javax.swing.JTextField();
        REM_3A = new javax.swing.JTextField();
        REM_2A = new javax.swing.JTextField();
        REM_1A = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jButton2.setText("INSERT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 530, 90, 23);

        jButton1.setText("<- BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 93, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("AVAILBILITY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 280, 97, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("TRAIN NO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 120, 124, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("REMAINING CC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 180, 124, 19);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("REMAINING SL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 240, 124, 19);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("REMAINING 3A");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 310, 124, 19);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("REMAINING 2A");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 370, 124, 19);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("REMAINING 1A");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 430, 124, 19);

        TRAIN_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRAIN_NOActionPerformed(evt);
            }
        });
        getContentPane().add(TRAIN_NO);
        TRAIN_NO.setBounds(460, 120, 90, 30);

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(620, 530, 100, 23);
        getContentPane().add(REM_CC);
        REM_CC.setBounds(460, 180, 90, 30);
        getContentPane().add(REM_SL);
        REM_SL.setBounds(460, 240, 92, 30);
        getContentPane().add(REM_3A);
        REM_3A.setBounds(460, 302, 92, 30);
        getContentPane().add(REM_2A);
        REM_2A.setBounds(460, 362, 90, 30);
        getContentPane().add(REM_1A);
        REM_1A.setBounds(460, 422, 90, 30);

        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 530, 100, 23);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAIN NO", "REM CC", "REM SL", "REM 3A", "REM 2A", "REM 1A"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 110, 590, 250);

        jButton4.setText("DISPLAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 530, 100, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miini/imgonline-com-ua-ReplaceColor-rWxUlG475Vai8u.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1280, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TRAIN_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRAIN_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRAIN_NOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        connect c = new connect();
        c.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
           String sql1 = "select * from AVAILABILITY where TRAIN_NO = '"+TRAIN_NO.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Train Details Already Exists");
            }
            else{
                if(TRAIN_NO.getText().equals("") || REM_CC.getText().equals("") ||  REM_SL.getText().equals("") || REM_3A.getText().equals("")  || REM_2A.getText().equals("") || REM_1A.getText().equals("")){
                        JOptionPane.showMessageDialog(this,"Invalid Input!");
                }
                else{
                    try{
                        String sql ="insert into AVAILABILITY values(?,?,?,?,?,?)";
                        ps=con.prepareStatement(sql);
                        ps.setInt(1,Integer.parseInt(TRAIN_NO.getText()));
                        ps.setInt(2,Integer.parseInt(REM_CC.getText()));
                        ps.setInt(3,Integer.parseInt(REM_SL.getText()));
                        ps.setInt(4,Integer.parseInt(REM_3A.getText()));
                        ps.setInt(5,Integer.parseInt(REM_2A.getText()));
                        ps.setInt(6,Integer.parseInt(REM_1A.getText()));
                        ps.execute();
                        JOptionPane.showMessageDialog(this,"Train Details Inserted");
                    }
                    catch(SQLException ex){
                        Logger.getLogger(availability.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    
                }
                
            }

        }
        catch(Exception ex){
           Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex.getMessage());
 
        }                       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
String sql = "select * from AVAILABILITY where TRAIN_NO = '"+TRAIN_NO.getText()+"'";
st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
rs = st.executeQuery(sql);
if(rs.next()){
TRAIN_NO.setText(rs.getString(1));
REM_CC.setText(rs.getString(2));
REM_SL.setText(rs.getString(3));
REM_3A.setText(rs.getString(4));
REM_2A.setText(rs.getString(5));
REM_1A.setText(rs.getString(6));
//String s=rs.getString(13);
JOptionPane.showMessageDialog(this, "Record Found!");
}
else
JOptionPane.showMessageDialog(this, "Record NotFound!");
}
catch (SQLException ex) {
Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
JOptionPane.showMessageDialog(this, ex.getMessage());
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // SQL command data stored in String datatype
            String sql = "select * from AVAILABILITY";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String tno = rs.getString("TRAIN_NO");
                String cc = rs.getString("REM_CC");
                String sl = rs.getString("REM_SL");
                String a3 = rs.getString("REM_3A");
                String a2 = String.valueOf(rs.getString("REM_2A"));
                String a1 = String.valueOf(rs.getString("REM_1A"));
                
                Object[] row = { tno,cc,sl,a3,a2,a1};
                DefaultTableModel model = (DefaultTableModel) tab.getModel();
                model.addRow(row);
            }
        }

        catch (SQLException e) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TRAIN_NO.setText(null);
        REM_CC.setText(null);
        REM_SL.setText(null);
        REM_3A.setText(null);
        REM_2A.setText(null);
        REM_1A.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(availability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new availability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField REM_1A;
    private javax.swing.JTextField REM_2A;
    private javax.swing.JTextField REM_3A;
    private javax.swing.JTextField REM_CC;
    private javax.swing.JTextField REM_SL;
    private javax.swing.JTextField TRAIN_NO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
