/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miini;
import java.sql.DriverManager;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.sql.Connection;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Darshan
 */
public class passenger extends javax.swing.JFrame {
Connection con;
Statement st;
PreparedStatement ps;
ResultSet rs;
    /**
     * Creates new form passenger
     */
    public passenger() {
        initComponents();
        try{
Class.forName("oracle.jdbc.OracleDriver");
//JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
con = DriverManager.getConnection("jdbc:oracle:thin:@JK:1521:XE",
                        "system", "jk");
//JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(passenger.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
catch(ClassNotFoundException ex){
Logger.getLogger(passenger.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        P_Id = new javax.swing.JTextField();
        F_Name = new javax.swing.JTextField();
        L_Name = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        INSERT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        DISPLAY = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1260, 720));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("PASSENGER ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 120, 110, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("FIRST NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 170, 110, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText(" LAST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 220, 100, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("GENDER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 270, 80, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText(" PHONE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 320, 70, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText(" AGE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 370, 37, 16);
        getContentPane().add(P_Id);
        P_Id.setBounds(453, 105, 125, 22);

        F_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_NameActionPerformed(evt);
            }
        });
        getContentPane().add(F_Name);
        F_Name.setBounds(453, 158, 125, 22);
        getContentPane().add(L_Name);
        L_Name.setBounds(453, 213, 125, 22);
        getContentPane().add(Gender);
        Gender.setBounds(453, 268, 125, 22);
        getContentPane().add(Phone);
        Phone.setBounds(453, 323, 125, 22);
        getContentPane().add(Age);
        Age.setBounds(453, 378, 125, 22);

        jButton1.setText("<- BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 80, 23);

        INSERT.setText("INSERT");
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });
        getContentPane().add(INSERT);
        INSERT.setBounds(150, 490, 90, 23);

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCH);
        SEARCH.setBounds(290, 490, 90, 23);

        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR);
        CLEAR.setBounds(430, 490, 90, 23);

        DISPLAY.setText("DISPLAY");
        DISPLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAYActionPerformed(evt);
            }
        });
        getContentPane().add(DISPLAY);
        DISPLAY.setBounds(570, 490, 90, 23);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PASSENGER ID", "FIRST NAME", "LAST NAME", "GENDER", "PHONE", "AGE"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(670, 120, 560, 260);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("PASSENGER");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 30, 90, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miini/imgonline-com-ua-ReplaceColor-kYQ2GrDmpAQAG439 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -120, 1250, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_NameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        connect c = new connect();
        c.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        // TODO add your handling code here:
        try{
           String sql1 = "select * from PASSENGER where P_ID = '"+P_Id.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Passenger ID Already Exists");
            }
            else{
                if(P_Id.getText().equals("") || F_Name.getText().equals("") ||  L_Name.getText().equals("") || Age.getText().equals("")  || Gender.getText().equals("") || Phone.getText().equals("")){
                        JOptionPane.showMessageDialog(this,"Invalid Input!");
                }
                else{
                    try{
                        String sql ="insert into PASSENGER values(?,?,?,?,?,?)";
                        ps=con.prepareStatement(sql);
                        ps.setString(1,P_Id.getText());
                        ps.setString(2,F_Name.getText());
                        ps.setString(3,L_Name.getText());
                        ps.setInt(6,Integer.parseInt(Age.getText()));
                        ps.setString(4,Gender.getText());
                        ps.setString(5,Phone.getText());
                        ps.execute();
                        JOptionPane.showMessageDialog(this,"Passenger Inserted");
                    }
                    catch(SQLException ex){
                        Logger.getLogger(passenger.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    
                }
                
            }

        }
        catch(Exception ex){
           Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex.getMessage());
 
        }
    }//GEN-LAST:event_INSERTActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
                try {
String sql = "select * from PASSENGER where P_Id = '"+P_Id.getText()+"'";
st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
rs = st.executeQuery(sql);
if(rs.next()){
P_Id.setText(rs.getString(1));
F_Name.setText(rs.getString(2));
L_Name.setText(rs.getString(3));
Gender.setText(rs.getString(4));
Phone.setText(rs.getString(5));
Age.setText(rs.getString(6));
//String s=rs.getString(13);
JOptionPane.showMessageDialog(this, "Record Found!");
}
else
JOptionPane.showMessageDialog(this, "Record NotFound!");
}
catch (SQLException ex) {
Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
JOptionPane.showMessageDialog(this, ex.getMessage());
}

    }//GEN-LAST:event_SEARCHActionPerformed

    private void DISPLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAYActionPerformed
        // TODO add your handling code here:
        try {
            // SQL command data stored in String datatype
            String sql = "select * from PASSENGER";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String id = rs.getString("P_ID");
                String fname = rs.getString("F_NAME");
                String lname = rs.getString("L_NAME");
                String gen = rs.getString("Gender");
                String phone = String.valueOf(rs.getString("Phone"));
                String age = String.valueOf(rs.getString("Age"));
                System.out.println(id + "\t\t" + fname
                                   + "\t\t" + lname);
                
                Object[] row = { id,fname,lname,gen,phone,age};
                DefaultTableModel model = (DefaultTableModel) tab.getModel();
                model.addRow(row);
            }
        }

        catch (SQLException e) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DISPLAYActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        P_Id.setText(null);
        F_Name.setText(null);
        L_Name.setText(null);
        Gender.setText(null);
        Phone.setText(null);
        Age.setText(null);
    }//GEN-LAST:event_CLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DISPLAY;
    private javax.swing.JTextField F_Name;
    private javax.swing.JTextField Gender;
    private javax.swing.JButton INSERT;
    private javax.swing.JTextField L_Name;
    private javax.swing.JTextField P_Id;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton SEARCH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
