/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miini;
import java.sql.DriverManager;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.sql.Connection;
import java.util.logging.Logger;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milin
 */
public class station extends javax.swing.JFrame {
Connection con;
Statement st;
PreparedStatement ps;
ResultSet rs;
    /**
     * Creates new form station
     */
    public station() {
        initComponents();
        try{
Class.forName("oracle.jdbc.OracleDriver");
//JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
con = DriverManager.getConnection("jdbc:oracle:thin:@JK:1521:XE",
                        "system", "jk");
//JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(passenger.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
catch(ClassNotFoundException ex){
Logger.getLogger(passenger.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        STATION_ID = new javax.swing.JTextField();
        STATION_NAME = new javax.swing.JTextField();
        INSERT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        DISPLAY = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("STATION NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 330, 120, 29);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("STATION ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 240, 100, 30);

        STATION_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STATION_IDActionPerformed(evt);
            }
        });
        getContentPane().add(STATION_ID);
        STATION_ID.setBounds(470, 240, 114, 25);
        getContentPane().add(STATION_NAME);
        STATION_NAME.setBounds(470, 330, 114, 25);

        INSERT.setText("INSERT");
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });
        getContentPane().add(INSERT);
        INSERT.setBounds(120, 530, 72, 23);

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCH);
        SEARCH.setBounds(270, 530, 80, 23);

        DISPLAY.setText("DISPLAY");
        DISPLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAYActionPerformed(evt);
            }
        });
        getContentPane().add(DISPLAY);
        DISPLAY.setBounds(435, 530, 90, 23);

        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR);
        CLEAR.setBounds(610, 530, 72, 23);

        jButton5.setText("<- BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 0, 76, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("STATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 300, 70, 20);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STATION ID", "STATION NAME"
            }
        ));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(720, 110, 452, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miini/imgonline-com-ua-ReplaceColor-RwlHy5Hoz6d.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1290, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void STATION_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STATION_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STATION_IDActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select * from STATION where STATION_ID = '"+STATION_ID.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(sql);
            if(rs.next()){
                STATION_ID.setText(rs.getString(1));
                STATION_NAME.setText(rs.getString(2));
            //String s=rs.getString(13);
            JOptionPane.showMessageDialog(this, "Record Found!");
            }
            else
            JOptionPane.showMessageDialog(this, "Record NotFound!");
            }
            catch (SQLException ex) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
}
    }//GEN-LAST:event_SEARCHActionPerformed

    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        // TODO add your handling code here:
        try{
           String sql1 = "select * from STATION where STATION_ID = '"+STATION_ID.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(sql1);
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "STATION ID Already Exists");
            }
            else{
                if(STATION_ID.getText().equals("") || STATION_NAME.getText().equals("")){
                        JOptionPane.showMessageDialog(this,"Invalid Input!");
                }
                else{
                    try{
                        String sql ="insert into STATION values(?,?)";
                        ps=con.prepareStatement(sql);
                        ps.setString(1,STATION_ID.getText());
                        ps.setString(2,STATION_NAME.getText());               
                        ps.execute();
                        JOptionPane.showMessageDialog(this,"STATION Inserted");
                    }
                    catch(SQLException ex){
                        Logger.getLogger(passenger.class.getName()).log(Level.SEVERE,null, ex);
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    
                }
                
            }

        }
        catch(Exception ex){
           Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(this, ex.getMessage());
 
        }
    }//GEN-LAST:event_INSERTActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        connect c = new connect();
        c.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        STATION_ID.setText(null);
        STATION_NAME.setText(null);
    }//GEN-LAST:event_CLEARActionPerformed

    private void DISPLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAYActionPerformed
        // TODO add your handling code here:
         try {
            // SQL command data stored in String datatype
            String sql = "select * from STATION";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String cl = rs.getString(1);
                String price = String.valueOf(rs.getString(2));
                
                Object[] row = {cl,price};
                DefaultTableModel model = (DefaultTableModel) tab.getModel();
                model.addRow(row);
            }
        }

        catch (SQLException e) {
            Logger.getLogger(passenger.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DISPLAYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(station.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new station().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton DISPLAY;
    private javax.swing.JButton INSERT;
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField STATION_ID;
    private javax.swing.JTextField STATION_NAME;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
